background_opacity: 1.0
live_config_reload: true
dynamic_title: true

window:
  title: Alacritty
  decorations: full

scrolling:
  history: 10000
  multiplier: 1

font:
  normal:
    family: GohuNew
    style: Regular
  size: 10.0

colors:
  primary:
    background: '#0a0b0e'
    foreground: '#ffffff'

  cursor:
    text: '#000000'
    cursor: '#ffffff'

  normal:
    black:   '#1b1d1e'
    red:     '#d54e53'
    green:   '#b9ca4a'
    yellow:  '#e6c547'
    blue:    '#7aa6da'
    magenta: '#c397d8'
    cyan:    '#70c0ba'
    white:   '#eaeaea'

  bright:
    black:   '#666666'
    red:     '#ff3334'
    green:   '#9ec400'
    yellow:  '#e7c547'
    blue:    '#7aa6da'
    magenta: '#b77ee0'
    cyan:    '#54ced6'
    white:   '#ffffff'

cursor:
  style: Block
  unfocused_hollow: true

shell:
  program: /bin/bash
  args:
    - --login

mouse:
  hide_when_typing: true
  url:
    launcher:
      program: xdg-open
      args: []
    modifiers: None

mouse_bindings:
  - mouse: Middle
    action: PasteSelection

key_bindings:
  - { key: F11,                           action: ToggleFullscreen            }
  - { key: C,        mods: Control|Shift, action: Copy                        }
  - { key: Copy,                          action: Copy                        }
  - { key: V,        mods: Control|Shift, action: Paste                       }
  - { key: Paste,                         action: Paste                       }
  - { key: Insert,   mods: Shift,         action: PasteSelection              }
  - { key: Key0,     mods: Control,       action: ResetFontSize               }
  - { key: Add,      mods: Control,       action: IncreaseFontSize            }
  - { key: Minus,    mods: Control,       action: DecreaseFontSize            }
  - { key: Up,       mods: Control|Shift, action: ScrollLineUp                }
  - { key: Down,     mods: Control|Shift, action: ScrollLineDown              }
  - { key: L,        mods: Control,       chars: "\x0c"                       }
  - { key: PageUp,   mods: Shift,         action: ScrollPageUp,    mode: ~Alt }
  - { key: PageDown, mods: Shift,         action: ScrollPageDown,  mode: ~Alt }
  - { key: Home,     mods: Shift,         action: ScrollToTop,     mode: ~Alt }
  - { key: End,      mods: Shift,         action: ScrollToBottom,  mode: ~Alt }
